name: apply
on:
  pull_request:
    types: [opened, edited]
jobs:
  process:
    name: approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Proces
        run: |
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Comment Author: ${{ github.event.comment.user.login }}"
          echo "PR Number: ${{ github.event.issue.number }}"
          echo "Repository: ${{ github.repository }}"
          if [[ "${{ github.event.comment.body }}" == "atlantis apply" ]]; then
              echo "need second lvl of approval"
              exit 1
            else
              echo  "good to apply"
            fi
