name: t20
on:
  issue_comment:
    types:
      [created, edited]
      
jobs:
  qwerty:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Process Comment
        run: |
          echo "Comment Body: ${{ github.event.comment.body }}"
          echo "Comment Author: ${{ github.event.comment.user.login }}"
          echo "PR Number: ${{ github.event.issue.number }}"
          echo "Repository: ${{ github.repository }}"
          if [ "$(curl -sSL -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            'https://api.github.com/repos/${{ github.repository }}"/${{ github.event.issue.number }}/reviews?state=APPROVED' | jq '. | length')" -lt -1 ]; then
              echo "Cannot apply changes. Insufficient PR approvals."
              exit 1
          fi
          if [[ "${{ github.event.comment.body }}" == "atlantis apply" ]]; then
              echo "need second lvl of approval"
              exit 1
            else
              echo  "good to apply"
            fi
