name: issue-comment-CI-test

on:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        gh pr checkout ${{ github.event.issue.number }}
        
        echo "Comment Body: ${{ github.event.comment.body }}"
        echo "Comment Author: ${{ github.event.comment.user.login }}"
        echo "PR Number: ${{ github.event.issue.number }}"
        echo "Repository: ${{ github.repository }}"
        if [[ "${{ github.event.comment.body }}" == "atlantis apply" ]]; then
        echo "need second lvl of approval"
        exit 1
        else
        echo  "good to apply"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
